services:
  # =============================================
  # Sinchronize
  # =============================================
  application.chats.sincronizer:
    class: '../../../application/chats/synchronize/ChatSynchronizeService'
    arguments:
      - '@infrastructure.repository.mongo.chat_repository'
      - '@shared.logger'
    public: true

  application.chats.list.chats_finder:
    class: '../../../application/chats/list/ChatsFinder'
    arguments:
      - '@infrastructure.repository.mongo.chat_read_repository'
    public: true

  # =============================================
  # QuerHandler
  # =============================================
  application.chats.list.get_chats_query_handler:
    class: '../../../application/chats/list/GetChatsQueryHandler'
    arguments:
      - '@application.chats.list.chats_finder'
    tags:
      - { name: 'queryHandler' }
    public: true
