services:
  # =============================================
  # UsesCase
  # =============================================
  application.messages.audio.audio_sender:
    class: '../../../application/messages/audio/AudioSender'
    arguments:
      - '@infrastructure.repository.whatsapp_instance'
      - '@application.runtime.runtime_manager'
    public: true

  application.messages.conctact.contact_sender:
    class: '../../../application/messages/contact/ContactSender'
    arguments:
      - '@infrastructure.repository.whatsapp_instance'
      - '@application.runtime.runtime_manager'
    public: true

  application.messages.document.document_sender:
    class: '../../../application/messages/document/DocumentSender'
    arguments:
      - '@infrastructure.repository.whatsapp_instance'
      - '@application.runtime.runtime_manager'
    public: true

  application.messages.image.image_sender:
    class: '../../../application/messages/image/ImageSender'
    arguments:
      - '@infrastructure.repository.whatsapp_instance'
      - '@application.runtime.runtime_manager'
    public: true

  application.messages.location.location_sender:
    class: '../../../application/messages/location/LocationSender'
    arguments:
      - '@infrastructure.repository.whatsapp_instance'
      - '@application.runtime.runtime_manager'
    public: true

  application.messages.reaction.reaction_sender:
    class: '../../../application/messages/reaction/ReactionSender'
    arguments:
      - '@infrastructure.repository.whatsapp_instance'
      - '@application.runtime.runtime_manager'
    public: true

  application.messages.sticker.sticker_sender:
    class: '../../../application/messages/sticker/StickerSender'
    arguments:
      - '@infrastructure.repository.whatsapp_instance'
      - '@application.runtime.runtime_manager'
    public: true

  application.messages.text.text_sender:
    class: '../../../application/messages/text/TextMessageSender'
    arguments:
      - '@infrastructure.repository.whatsapp_instance'
      - '@application.service.message_orchestrator'
    public: true

  application.messages.video.video_sender:
    class: '../../../application/messages/video/VideoSender'
    arguments:
      - '@infrastructure.repository.whatsapp_instance'
      - '@application.runtime.runtime_manager'
    public: true

  # =============================================
  # CommandHandlers
  # =============================================
  application.messages.audio.send_audio_command_handler:
    class: '../../../application/messages/audio/SendAudioCommandHandler'
    arguments:
      - '@application.messages.audio.audio_sender'
    tags:
      - { name: 'commandHandler' }
    public: true

  application.messages.contact.send_contact_command_handler:
    class: '../../../application/messages/contact/SendContactCommandHandler'
    arguments:
      - '@application.messages.conctact.contact_sender'
    tags:
      - { name: 'commandHandler' }
    public: true

  application.messages.document.send_document_command_handler:
    class: '../../../application/messages/document/SendDocumentCommandHandler'
    arguments:
      - '@application.messages.document.document_sender'
    tags:
      - { name: 'commandHandler' }
    public: true

  application.messages.image.send_image_command_handler:
    class: '../../../application/messages/image/SendImageCommandHandler'
    arguments:
      - '@application.messages.image.image_sender'
    tags:
      - { name: 'commandHandler' }
    public: true

  application.messages.location.send_location_command_handler:
    class: '../../../application/messages/location/SendLocationCommandHandler'
    arguments:
      - '@application.messages.location.location_sender'
    tags:
      - { name: 'commandHandler' }
    public: true

  application.messages.reaction.send_reaction_command_handler:
    class: '../../../application/messages/reaction/SendReactionCommandHandler'
    arguments:
      - '@application.messages.reaction.reaction_sender'
    tags:
      - { name: 'commandHandler' }
    public: true

  application.messages.sticker.send_sticker_command_handler:
    class: '../../../application/messages/sticker/SendStickerCommandHandler'
    arguments:
      - '@application.messages.sticker.sticker_sender'
    tags:
      - { name: 'commandHandler' }
    public: true

  application.messages.text.send_text_command_handler:
    class: '../../../application/messages/text/SendMessageCommandHandler'
    arguments:
      - '@application.messages.text.text_sender'
    tags:
      - { name: 'commandHandler' }
    public: true

  application.messages.video.send_video_command_handler:
    class: '../../../application/messages/video/SendVideoCommandHandler'
    arguments:
      - '@application.messages.video.video_sender'
    tags:
      - { name: 'commandHandler' }
    public: true

  # =============================================
  # Orchestrator
  # =============================================
  application.service.human_behavior:
    class: '../../../application/services/HumanBehaviorService'
    public: true

  application.service.limiter_factory:
    class: '../../../application/services/LimiterFactory'
    public: true

  application.service.message_orchestrator:
    class: '../../../application/services/MessageOrchestrator'
    arguments:
      - '@application.runtime.runtime_manager'
      - '@application.service.limiter_factory'
      - '@application.service.human_behavior'
    public: true
