services:
  # =============================================
  # Controllers
  # =============================================
  http.controller.instances.get.instances:
    class: ../../../infrastructure/http/controllers/instances/GetInstancesController
    arguments:
      - '@shared.query_bus'

  http.controller.instances.get.instance:
    class: ../../../infrastructure/http/controllers/instances/GetInstanceController
    arguments:
      - '@shared.query_bus'

  http.controller.get_qr:
    class: '../../../infrastructure/http/controllers/instances/GetQRController'
    arguments:
      - '@shared.query_bus'
    public: true

  http.controller.qr_status:
    class: '../../../infrastructure/http/controllers/instances/GetQRStatusController'
    arguments:
      - '@shared.query_bus'
    public: true

  http.controller.instance.creator:
    class: '../../../infrastructure/http/controllers/instances/CreateInstanceController'
    arguments:
      - '@shared.command_bus'
    public: true

  http.controller.instance.eraser:
    class: '../../../infrastructure/http/controllers/instances/DeleteInstanceController'
    arguments:
      - '@shared.command_bus'
    public: true

  http.controller.instance.disconect:
    class: '../../../infrastructure/http/controllers/instances/DisconnectInstanceController'
    arguments:
      - '@shared.command_bus'
    public: true
