# =============================================
# Instances Services
# =============================================
services:
  # =============================================
  # UsesCase
  # =============================================
  application.instance.list.instances_searcher:
    class: '../../../application/instances/list/InstancesSearcher'
    arguments:
      - '@infrastructure.repository.mongo.instance_read_repository'
    public: true

  application.instances.get.find_instance:
    class: '../../../application/instances/get/FindInstance'
    arguments:
      - '@infrastructure.repository.mongo.instance_read_repository'
    public: true

  application.instances.qr_code.status:
    class: '../../../application/instances/qr-code/status/QRCodeStatus'
    arguments:
      - '@infrastructure.repository.mongo.instance_read_repository'
    public: true

  application.instances.qr_code.searcher:
    class: '../../../application/instances/qr-code/get/QRCodeSearcher'
    arguments:
      - '@infrastructure.repository.mongo.instance_read_repository'
      - '@infrastructure.cache.nodecache_connection_store'
    public: true

  application.instances.create.instances_creator:
    class: ../../../application/instances/create/InstancesCreator
    arguments:
      - '@infrastructure.repository.whatsapp_instance'
      - '@application.runtime.runtime_manager'
    public: true

  application.instances.delete.instances_eraser:
    class: ../../../application/instances/delete/InstancesEraser
    arguments:
      - '@infrastructure.repository.whatsapp_instance'
      - '@application.runtime.runtime_manager'
    public: true

  application.instances.connect.instances_connect:
    class: ../../../application/instances/connect/InstancesConnect
    arguments:
      - '@application.runtime.runtime_manager'
    public: true

  application.instances.disconnect.instances_disconnect:
    class: ../../../application/instances/disconnect/InstancesDisconnect
    arguments:
      - '@application.runtime.runtime_manager'
    public: true

  # =============================================
  # QueryHandler
  # =============================================
  application.instances.list.list_instances_query_handler:
    class: '../../../application/instances/list/ListInstancesQueryHandler'
    arguments:
      - '@application.instance.list.instances_searcher'
    tags:
      - { name: 'queryHandler' }
    public: true

  application.intances.get.get_instance_query_handler:
    class: ../../../application/instances/get/GetInstanceQueryHandler
    arguments:
      - '@application.instances.get.find_instance'
    tags:
      - { name: 'queryHandler' }
    public: true

  application.instances.qr_code.status.query_handler:
    class: ../../../application/instances/qr-code/status/GetQRCodeStatusQueryHandler
    arguments:
      - '@application.instances.qr_code.status'
    tags:
      - { name: 'queryHandler' }
    public: true

  application.instances.qr_code.query_handler:
    class: ../../../application/instances/qr-code/get/GetQRCodeQueryHandler
    arguments:
      - '@application.instances.qr_code.searcher'
    tags:
      - { name: 'queryHandler' }
    public: true

  # =============================================
  # CommandHandler
  # =============================================
  application.instances.create.command_handler:
    class: ../../../application/instances/create/CreateInstanceCommandHandler
    arguments:
      - '@application.instances.create.instances_creator'
    tags:
      - { name: 'commandHandler' }
    public: true

  application.instances.delete.command_handler:
    class: ../../../application/instances/delete/DeleteInstanceCommandHandler
    arguments:
      - '@application.instances.delete.instances_eraser'
    tags:
      - { name: 'commandHandler' }
    public: true

  application.instances.connect.command_handler:
    class: ../../../application/instances/connect/ConnectInstanceCommandHandler
    arguments:
      - '@application.instances.connect.instances_connect'
    tags:
      - { name: 'commandHandler' }
    public: true

  application.instances.disconnect.command_handler:
    class: ../../../application/instances/disconnect/DisconnectInstanceCommandHandler
    arguments:
      - '@application.instances.disconnect.instances_disconnect'
    tags:
      - { name: 'commandHandler' }
    public: true
