# config/services/application.yaml
# =============================================
# Import services
# =============================================
# Handlers y servicios del Application Layer
imports:
  - { resource: ./instances/instances.yaml }
  - { resource: ./messages/application.yaml }
  - { resource: ./groups/application.yaml }
  - { resource: ./chats/application.yaml }
