# config/services/http.yaml
# Controllers y servicios HTTP
# =============================================
# Controllers y servicios HTTP
# =============================================
imports:
  - { resource: ./instances/http.yaml }
  - { resource: ./messages/http.yaml }
  - { resource: ./groups/http.yaml }
  - { resource: ./chats/http.yaml }
