# config/services/infrastructure.yaml
# Servicios de Infrastructure Layer
# =============================================
# Infrastructure Services
# =============================================
services:
  # =============================================
  # Persistence - MongoDB
  # =============================================
  infrastructure.database.connection:
    factory:
      class: '../../infrastructure/persistence/DatabaseConnectionFactory'
      method: 'create'
    arguments:
      - '@api.config'
      - '@shared.logger'
    # calls:
    #   - [connect, []]
    public: true

  infrastructure.repository.whatsapp_instance:
    class: '../../infrastructure/persistence/mongo/repositories/MongoWhatsAppInstanceRepository'
    public: true

  infrastructure.repository.mongo.instance_read_repository:
    class: '../../infrastructure/persistence/mongo/repositories/MongoWhatsAppInstanceReadRepository'
    public: true

  infrastructure.repository.mongo.chat_read_repository:
    class: '../../infrastructure/persistence/mongo/repositories/MongoChatReadRepository'
    public: true

  infrastructure.repository.mongo.chat_repository:
    class: '../../infrastructure/persistence/mongo/repositories/MongoChatRepository'
    public: true

  # =============================================
  # Baileys - WhatsApp
  # =============================================

  infrastructure.baileys.connection_manager:
    class: '../../infrastructure/baileys/BaileysConnectionManager'
    arguments:
      - '@infrastructure.repository.whatsapp_instance'
      - '@application.chats.sincronizer'
      - '@shared.logger'
      - '@infrastructure.metrics.message'
    public: true

  # =============================================
  # Metrics
  # =============================================
  infrastructure.metrics.message:
    class: '../../infrastructure/metrics/MessageMetrics'
  public: true
