# config/services/parameters.yaml
# Parámetros globales de la aplicación
# =============================================
# Factory Config
# =============================================
services:
  api.config:
    factory:
      class: ../../config/FactoryConfig
      method: 'loadConfig'
    public: true
