# config/services/shared.yaml
# =============================================
# Servicios compartidos (Shared Layer)
# =============================================

parameters:
  api.logger.config:
    level: 'info'
    transport:
      targets:
        - target: 'pino-pretty'
          options:
            colorize: 'true'
            translateTime: 'SYS:standard'
            ignore: 'pid,hostname'
        - target: 'pino/file'
          level: 'debug'
          options:
            # destination: "./logs/log.debug.file.log"
            mkdir: 'true'

services:
  # =============================================
  # Services
  # =============================================
  shared.logger:
    class: '../../infrastructure/loggers/pino-logger/PinoLogger'
    arguments:
      - '%api.logger.config%'
    public: true

  # Response Handler (Singleton)
  shared.response_handler:
    class: '../../shared/infrastructure/ResponseHandler'
    public: true

  # Error Handler
  shared.error_handler:
    class: '../../shared/infrastructure/ErrorHandler'
    arguments:
      - '@shared.logger'
    public: true
  # =============================================
  # Query Handler
  # =============================================
  shared.query_handler:
    class: ../../shared/infrastructure/query-bus/QueryHandlers
    arguments:
      - '!tagged queryHandler'
    public: true
  # =============================================
  # Query Bus
  # =============================================
  shared.query_bus:
    class: ../../shared/infrastructure/query-bus/in-memory/InMemoryQueryBus
    arguments:
      - '@shared.query_handler'
    public: true
  # =============================================
  # Event Bus
  # =============================================
  shared.event_bus:
    class: ../../shared/infrastructure/event-bus/in-memory/NodeEventBus
    public: true
  # =============================================
  # Command Handler
  # =============================================
  shared.command_handler:
    class: ../../shared/infrastructure/command-bus/CommandHandlers
    arguments:
      - '!tagged commandHandler'
    public: true

  # =============================================
  # Command Bus
  # =============================================
  shared.command_bus:
    class: ../../shared/infrastructure/command-bus/in-memory/InMemoryCommandBus
    arguments:
      - '@shared.command_handler'
    public: true

  # =============================================
  # Runtime Managers
  # =============================================
  application.runtime.runtime_manager:
    class: '../../application/runtime/RuntimeManager'
    arguments:
      - '@application.runtime.runtime_registry'
      - '@infrastructure.repository.whatsapp_instance'
      - '@application.runtime.whatsapp_runtime_factory'
      - '@shared.logger'
    public: true

  application.runtime.runtime_registry:
    class: '../../application/runtime/RuntimeRegistry'
    arguments: []
    public: true

  application.runtime.whatsapp_runtime_factory:
    class: '../../application/runtime/WhatsAppRuntimeFactory'
    arguments:
      - '@infrastructure.repository.whatsapp_instance'
      - '@application.chats.sincronizer'
      - '@infrastructure.http.webhooks.webhook_service'
      - '@shared.logger'
      - '@infrastructure.cache.nodecache_connection_store'
      - '@shared.event_bus'

  # =============================================
  # Runtime Managers
  # =============================================
